# Generated by Django 4.0.2 on 2022-02-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_section',
            name='paragraph',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='books_section',
            name='section_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
