# Generated by Django 4.0.2 on 2022-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_section_paragraph_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books_section',
            old_name='section_name',
            new_name='heading',
        ),
        migrations.AlterField(
            model_name='books_section',
            name='paragraph',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
    ]
