# Generated by Django 4.0.2 on 2022-02-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_section_name_books_section_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_section',
            name='paragraph',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
