# Generated by Django 4.0.2 on 2022-02-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_section_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_section',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
