# Generated by Django 4.0.2 on 2022-02-24 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_section_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_section',
            name='paragraph',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='books_section',
            name='self_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
